### ISSUE TITLE
Unable to send email alert

### ISSUE THREAD

**Issue by dbelancic** [jamesoff/simplemonitor#107]
I've been trying to setup SimpleMonitor, but whatever I do I can't seem to be able to send an email alert, I always get this error:

2018-08-04 10:34:23    ERROR (simplemonitor.alerter-unknown) couldn't send mail
Traceback (most recent call last):
  File "E:\Programi\jamesoff-simplemonitor-d062631\Alerters\mail.py", line 116, in send_alert
    server = smtplib.SMTP(self.mail_host, self.mail_port)
  File "C:\Python27\lib\smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "C:\Python27\lib\smtplib.py", line 317, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "C:\Python27\lib\smtplib.py", line 292, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "C:\Python27\lib\socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 11001] getaddrinfo failed

I am testing with the fail monitor

**Comment by jamesoff** [comment]
`getaddrinfo failed ` is the key here I think, it can't look up the IP of your specified mail server in DNS.

Can you check you can resolve the value you've set for `host` on your email alerter?

**Comment by rterbush** [comment]
Hope you don't mind me reopening this.

Having the same issue resolving smtp.gmail.com using simplemonitor v1.9. No problem resolving this host from command line using nslookup.

Running on a Windows machine, Server 2019.

This also works from the python shell:
```
>>> socket.getaddrinfo('smtp.gmail.com', 587)
[(<AddressFamily.AF_INET: 2>, 0, 0, '', ('108.177.8.108', 587))]
```
