### ISSUE TITLE
Import Errors When Launching Simplemonitor

### ISSUE THREAD

**Issue by haderp** [jamesoff/simplemonitor#1162]
When trying to load the simple monitor the following errors occur:

Traceback (most recent call last):
  File "/home/user/simplemonitor/bin/simplemonitor", line 5, in <module>
    from simplemonitor.monitor import main
  File "/home/user/simplemonitor/lib/python3.9/site-packages/simplemonitor/monitor.py", line 10, in <module>
    from .simplemonitor import SimpleMonitor
  File "/home/user/simplemonitor/lib/python3.9/site-packages/simplemonitor/simplemonitor.py", line 15, in <module>
    from .Alerters.alerter import Alerter
  File "/home/user/simplemonitor/lib/python3.9/site-packages/simplemonitor/Alerters/__init__.py", line 5, in <module>
    from .bulksms import BulkSMSAlerter
  File "/home/user/simplemonitor/lib/python3.9/site-packages/simplemonitor/Alerters/bulksms.py", line 7, in <module>
    from ..Monitors.monitor import Monitor
  File "/home/user/simplemonitor/lib/python3.9/site-packages/simplemonitor/Monitors/__init__.py", line 21, in <module>
    from .network import (
  File "/home/user/simplemonitor/lib/python3.9/site-packages/simplemonitor/Monitors/network.py", line 13, in <module>
    import OpenSSL.SSL
  File "/home/user/simplemonitor/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/home/user/simplemonitor/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1556, in <module>
    class X509StoreFlags(object):
  File "/home/user/simplemonitor/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1577, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

Any feedback on how to resolve the errors would be greatly appreciated.

**Comment by jamesoff** [comment]
Could you try `pip install --upgrade pyOpenSSL` for the virtualenv simplemonitor is installed in?

**Comment by haderp** [comment]
Upgrading pyOpenSSL after install installing simplemonitor resolved the issue.  When installing simplemonitor using `pip install simplemonitor` it installs pyOpenSSL-20.0.1 and will give that error every time you try to launch.  Once upgraded everything works as expected.  Thanks for the direction as I've been chasing the root cause of the error for a week without finding the exact offender.

**Comment by jamesoff** [comment]
Thanks for confirming. Should probably look at cutting a new release soon!

**Comment by haderp** [comment]
Awesome, I look forward to it.  After trying all of the opensource/free solutions available yours is definitely the best for monitoring a small home lan without a ton of overhead and features that aren't geared towards a small network.  Thanks for your work and time.

**Comment by jamesoff** [comment]
Thanks for the feedback, really appreciate it <3

**Comment by steven-geo** [comment]
Looks like this was resolved in v1.12. Issue closed?
