### ISSUE TITLE
Remote network logging doesn't seem to work in current master

### ISSUE THREAD

**Issue by tbendiksen** [jamesoff/simplemonitor#119]
Works in release, but unless I have something configured wrong or missed something current master doesn't seem to work. 
Same config used on both. 
Example on current branch failing:
This is the server:
==== 
[root@server-hostname simplemonitor]# python monitor.py -f global.ini -d
Warning: --debug is deprecated; use --log-level=debug
2018-09-07 14:09:50    ERROR (simplemonitor) Could not enable colorlog
2018-09-07 14:09:50     INFO (simplemonitor) === SimpleMonitor v1.7
2018-09-07 14:09:50     INFO (simplemonitor) Loading main config from global.ini
2018-09-07 14:09:50     INFO (simplemonitor) Loading monitor config from /srv/simplemonitor/monitors.ini
2018-09-07 14:09:50     INFO (simplemonitor) === Loading monitors
2018-09-07 14:09:50     INFO (simplemonitor) Adding host monitor localhost: checking host localhost is pingable
2018-09-07 14:09:50  WARNING (simplemonitor) Ignoring monitor localhost-remote-disk because it's only for host client-hostname
2018-09-07 14:09:50     INFO (simplemonitor) --- Loaded 1 monitors
2018-09-07 14:09:50     INFO (simplemonitor) === Loading loggers
2018-09-07 14:09:50     INFO (simplemonitor) Adding json logger json: Writing JSON file to /var/www/html/simplemonitor/status.json
2018-09-07 14:09:50     INFO (simplemonitor) Adding html logger html: Writing HTML page to /var/www/html/simplemonitor/status.html
2018-09-07 14:09:50     INFO (simplemonitor) --- Loaded 2 loggers
2018-09-07 14:09:50     INFO (simplemonitor) === Loading alerters
2018-09-07 14:09:50     INFO (simplemonitor) --- Loaded 0 alerters
2018-09-07 14:09:50     INFO (simplemonitor) Starting remote listener thread
2018-09-07 14:09:50     INFO (simplemonitor) === Starting... (loop runs every 5s) Hit ^C to stop
2018-09-07 14:09:50    DEBUG (simplemonitor) Starting loop with joblist ['localhost']
2018-09-07 14:09:50    DEBUG (simplemonitor) Trying monitor: localhost
2018-09-07 14:09:50     INFO (simplemonitor) monitor passed: localhost
2018-09-07 14:09:51    DEBUG (simplemonitor.logger.networklistener) Got connection from 10.44.44.53
2018-09-07 14:09:51    DEBUG (simplemonitor.logger.networklistener) Finished receiving from 10.44.44.53
2018-09-07 14:09:51    DEBUG (simplemonitor.logger.networklistener) Computed my digest to be %%�3f�|z4�����; remote is %%�3f�|z4�����
2018-09-07 14:09:51     INFO (simplemonitor) trying remote monitor localhost_remote
2018-09-07 14:09:51     INFO (simplemonitor) trying remote monitor localhost-remote-disk
2018-09-07 14:09:51     INFO (simplemonitor) trying remote monitor localhost_remote_fail
2018-09-07 14:09:55    DEBUG (simplemonitor) Starting loop with joblist ['localhost']
2018-09-07 14:09:55    DEBUG (simplemonitor) Trying monitor: localhost
2018-09-07 14:09:55     INFO (simplemonitor) monitor passed: localhost
2018-09-07 14:09:55     INFO (simplemonitor) remote logging for localhost_remote
2018-09-07 14:09:55     INFO (simplemonitor) remote logging for localhost-remote-disk
2018-09-07 14:09:55     INFO (simplemonitor) remote logging for localhost_remote_fail
2018-09-07 14:09:55     INFO (simplemonitor) remote logging for localhost_remote
MonitorHost instance has no attribute 'running_on'
2018-09-07 14:09:55    ERROR (simplemonitor) exception while logging remote monitors
Traceback (most recent call last):
  File "/srv/simplemonitor/simplemonitor.py", line 138, in log_result
    self.remote_monitors[key].log_result(key, logger)
  File "/srv/simplemonitor/Monitors/monitor.py", line 215, in log_result
    logger.save_result(name, self.type, self.get_params(), result, self.last_result)
TypeError: save_result() takes exactly 1 argument (6 given)
.^CTraceback (most recent call last):
  File "monitor.py", line 480, in <module>
    main()
  File "monitor.py", line 431, in main
    time.sleep(interval)
KeyboardInterrupt

On the client:
[root@client-hostname simplemonitor-master]# python monitor.py -f monitor.ini -d
Warning: --debug is deprecated; use --log-level=debug
2018-09-07 14:09:51    ERROR (simplemonitor) Could not enable colorlog
2018-09-07 14:09:51     INFO (simplemonitor) === SimpleMonitor v1.7
2018-09-07 14:09:51     INFO (simplemonitor) Loading main config from monitor.ini
2018-09-07 14:09:51     INFO (simplemonitor) Loading monitor config from monitors.ini
2018-09-07 14:09:51     INFO (simplemonitor) === Loading monitors
2018-09-07 14:09:51     INFO (simplemonitor) Adding host monitor localhost_remote: checking host localhost is pingable
2018-09-07 14:09:51     INFO (simplemonitor) Adding host monitor localhost_remote_fail: checking host 172.18.1.1 is pingable
2018-09-07 14:09:51     INFO (simplemonitor) Adding diskspace monitor localhost-remote-disk: Checking for at least 2.44GiB free space on /tmp
2018-09-07 14:09:51     INFO (simplemonitor) --- Loaded 3 monitors
2018-09-07 14:09:51     INFO (simplemonitor) === Loading loggers
2018-09-07 14:09:51     INFO (simplemonitor) Adding network logger network: Sending monitor results to server-hostname:4321
2018-09-07 14:09:51     INFO (simplemonitor) --- Loaded 1 loggers
2018-09-07 14:09:51     INFO (simplemonitor) === Loading alerters
2018-09-07 14:09:51     INFO (simplemonitor) --- Loaded 0 alerters
2018-09-07 14:09:51     INFO (simplemonitor) === Starting... (loop runs every 25s) Hit ^C to stop
2018-09-07 14:09:51    DEBUG (simplemonitor) Starting loop with joblist ['localhost_remote', 'localhost-remote-disk', 'localhost_remote_fail']
2018-09-07 14:09:51    DEBUG (simplemonitor) Trying monitor: localhost_remote
2018-09-07 14:09:51     INFO (simplemonitor) monitor passed: localhost_remote
2018-09-07 14:09:51    DEBUG (simplemonitor) Trying monitor: localhost-remote-disk
2018-09-07 14:09:51    ERROR (simplemonitor) monitor failed: localhost-remote-disk (1.96GiB free (98%))
2018-09-07 14:09:51    DEBUG (simplemonitor) Trying monitor: localhost_remote_fail
2018-09-07 14:09:51    ERROR (simplemonitor) monitor failed: localhost_remote_fail (Command '['ping', '-c1', '-W5', '172.18.1.1']' returned non-zero exit status 1)
2018-09-07 14:09:51    DEBUG (simplemonitor.logger-network) network logger: localhost_remote checking host localhost is pingable
2018-09-07 14:09:51    DEBUG (simplemonitor.logger-network) network logger: localhost-remote-disk Checking for at least 2.44GiB free space on /tmp
2018-09-07 14:09:51    DEBUG (simplemonitor.logger-network) network logger: localhost_remote_fail checking host 172.18.1.1 is pingable
^CTraceback (most recent call last):
  File "monitor.py", line 480, in <module>
    main()
  File "monitor.py", line 431, in main
    time.sleep(interval)
KeyboardInterrupt

--- 
The same setup and config works with 1.7.

**Comment by jamesoff** [comment]
The good news is: I can reproduce the issue.

Looking in to it!

**Comment by tbendiksen** [comment]
Works with this latest commit. Thanks a million.

**Comment by jamesoff** [comment]
Great to hear; apologies for the breakage :)
