### ISSUE TITLE
No start on Windows (module 'signal' has no attribute 'SIGHUP')

### ISSUE THREAD

**Issue by wsw70** [jamesoff/simplemonitor#216]
On Windows 10, `monitor` (commit https://github.com/jamesoff/simplemonitor/commit/cb72a17bc456944efca3a95a457e59d78483f059) fails to start with a basic configuration:

```
> more monitors.ini
[monitor]
interval=60

[localhost]
type=host
host=localhost
tolerance=2

>python monitor.py -v
Warning: --verbose is deprecated; use --log-level=info
2019-01-18 13:23:28     INFO (simplemonitor) === SimpleMonitor v1.7
2019-01-18 13:23:28     INFO (simplemonitor) Loading main config from monitors.ini
2019-01-18 13:23:28     INFO (simplemonitor) Loading monitor config from monitors.ini
Traceback (most recent call last):
  File "monitor.py", line 403, in <module>
    main()
  File "monitor.py", line 263, in main
    m = SimpleMonitor(allow_pickle=allow_pickle)
  File "D:\Seafile\dev\dev-perso\simplemonitor\simplemonitor.py", line 36, in __init__
    signal.signal(signal.SIGHUP, self.hup_loggers)
AttributeError: module 'signal' has no attribute 'SIGHUP'
```

**Comment by jamesoff** [comment]
Definitely shouldn't happen; there's supposed to be code to guard against that being fatal! I'll take a look.

**Comment by jamesoff** [comment]
@wsw70 could you try the `bugfix/216` branch and see if it fixes the issue for you?

**Comment by wsw70** [comment]
@jamesoff yes it does, thank you!
