### ISSUE TITLE
[Windows] UnboundLocalError: local variable 'certfile' referenced before assignment

### ISSUE THREAD

**Issue by trv** [jamesoff/simplemonitor#31]
When running on Windows 7, I get the following error log on startup:

```
>python monitor.py
SimpleMonitor v1.7
--> Loading main config from monitor.ini
--> Loading monitor config from monitors.ini
Unable to trap SIGHUP... maybe it doesn't exist on this platform.
Traceback (most recent call last):
  File "monitor.py", line 407, in <module>
    main()
  File "monitor.py", line 307, in main
    m = load_monitors(m, monitors_file, options.quiet)
  File "monitor.py", line 118, in load_monitors
    new_monitor = Monitors.network.MonitorHTTP(monitor, config_options)
  File "C:\Users\me\Downloads\jamesoff-simplemonitor-v1.6-27-g8e5249f\jamesoff-simplemonitor-8e5249f\Monitors\network.py", line 82, in __init__
    self.certfile = certfile
UnboundLocalError: local variable 'certfile' referenced before assignment
```

I fixed it by moving [lines 82-83 in Monitors/network.py](https://github.com/jamesoff/simplemonitor/blob/master/Monitors/network.py#L82-L83) to the end of the `if 'certfile' in config_options:` block starting on line 66.

This allows my non-https monitor to work properly, but I haven't tested it to see if that change breaks https monitors.

**Comment by hattesen** [comment]
Same problem on Mac OS-X El Capitan 10.11.5

Python version 2.7.11

simplemonitor version: jamesoff-simplemonitor-v1.6-27-g8e5249f


```
jamesoff-simplemonitor-8e5249f$ sudo python monitor.py --test
SimpleMonitor v1.7
--> Loading main config from monitor.ini
--> Loading monitor config from monitors.ini
Adding host monitor dr-ping
Traceback (most recent call last):
  File "monitor.py", line 407, in <module>
    main()
  File "monitor.py", line 307, in main
    m = load_monitors(m, monitors_file, options.quiet)
  File "monitor.py", line 118, in load_monitors
    new_monitor = Monitors.network.MonitorHTTP(monitor, config_options)
  File "/volume1/data/jamesoff-simplemonitor-8e5249f/Monitors/network.py", line 82, in __init__
    self.certfile = certfile
UnboundLocalError: local variable 'certfile' referenced before assignment
```

**Comment by jamesoff** [comment]
Thanks for the fix info @trv :)
