### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by waqarsomra** [jamesoff/simplemonitor#499]
i am fairly new to python. so need some help.
i have downloaded the files and tried to install "python setup.py install". but it throws a lot of syntax errors. I am using python 2.7 on centos 7. for your reference i am dumping all the errors i'm getting in console.
```
`byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/monitor.py to monitor.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/monitor.py", line 58
    def setup_signals() -> None:
                        ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/simplemonitor.py to simplemonitor.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/simplemonitor.py", line 19
    def __init__(self, allow_pickle: bool = True) -> None:
                                   ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/version.py to version.pyc
byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/winmonitor.py to winmonitor.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/winmonitor.py", line 35
    logger: logging.Logger, level: int = logging.DEBUG
          ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Alerters/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Alerters/alerter.py to alerter.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Alerters/alerter.py", line 30
    def __init__(self, config_options: dict = None) -> None:
                                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Alerters/bulksms.py to bulksms.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Alerters/bulksms.py", line 19
    def __init__(self, config_options: dict) -> None:
                                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Alerters/execute.py to execute.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Alerters/execute.py", line 17
    def __init__(self, config_options: dict) -> None:
                                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Alerters/fortysixelks.py to fortysixelks.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Alerters/fortysixelks.py", line 23
    def __init__(self, config_options: dict) -> None:
                                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Alerters/mail.py to mail.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Alerters/mail.py", line 18
    def __init__(self, config_options: dict) -> None:
                                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Alerters/nc.py to nc.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Alerters/nc.py", line 20
    def __init__(self, config_options: dict) -> None:
                                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Alerters/pushbullet.py to pushbullet.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Alerters/pushbullet.py", line 16
    def __init__(self, config_options: dict) -> None:
                                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Alerters/pushover.py to pushover.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Alerters/pushover.py", line 17
    def __init__(self, config_options: dict) -> None:
                                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Alerters/ses.py to ses.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Alerters/ses.py", line 23
    def __init__(self, config_options: dict) -> None:
                                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Alerters/slack.py to slack.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Alerters/slack.py", line 24
    def __init__(self, config_options: dict) -> None:
                                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Alerters/syslogger.py to syslogger.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Alerters/syslogger.py", line 15
    def send_alert(self, name: str, monitor: Monitor) -> None:
                             ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Alerters/telegram.py to telegram.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Alerters/telegram.py", line 17
    def __init__(self, config_options: dict) -> None:
                                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Loggers/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Loggers/db.py to db.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Loggers/db.py", line 51
    def __init__(self, config_options: dict) -> None:
                                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Loggers/file.py to file.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Loggers/file.py", line 28
    def __init__(self, config_options: dict = None) -> None:
                                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Loggers/logger.py to logger.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Loggers/logger.py", line 19
    def __init__(self, config_options: dict) -> None:
                                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Loggers/mqtt.py to mqtt.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Loggers/mqtt.py", line 29
    def __init__(self, config_options: dict = None) -> None:
                                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Loggers/network.py to network.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Loggers/network.py", line 30
    def __init__(self, config_options: dict) -> None:
                                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Monitors/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Monitors/compound.py to compound.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Monitors/compound.py", line 21
    def __init__(self, name: str, config_options: dict) -> None:
                           ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Monitors/file.py to file.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Monitors/file.py", line 18
    def run_test(self) -> bool:
                       ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Monitors/hass.py to hass.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Monitors/hass.py", line 15
    def __init__(self, name: str, config_options: dict) -> None:
                           ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Monitors/host.py to host.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Monitors/host.py", line 24
    def _size_string_to_bytes(s: str) -> Optional[int]:
                               ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Monitors/monitor.py to monitor.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Monitors/monitor.py", line 49
    self, name: str = "unnamed", config_options: Optional[dict] = None
              ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Monitors/network.py to network.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Monitors/network.py", line 36
    def __init__(self, name: str, config_options: dict) -> None:
                           ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Monitors/ring.py to ring.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Monitors/ring.py", line 23
    def __init__(self, name: str, config_options: dict) -> None:
                           ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/Monitors/service.py to service.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/Monitors/service.py", line 27
    def __init__(self, name: str, config_options: dict) -> None:
                           ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/util/__init__.py to __init__.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/util/__init__.py", line 37
    config_options: dict, key: str, **kwargs: Any
                  ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/simplemonitor/util/envconfig.py to envconfig.pyc
  File "build/bdist.linux-x86_64/egg/simplemonitor/util/envconfig.py", line 13
    def __init__(self, *args: Any, **kwargs: Any) -> None:
                            ^
SyntaxError: invalid syntax

creating build/bdist.linux-x86_64/egg/EGG-INFO
copying simplemonitor.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying simplemonitor.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying simplemonitor.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying simplemonitor.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying simplemonitor.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying simplemonitor.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/simplemonitor-1.9.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing simplemonitor-1.9.0-py2.7.egg
Copying simplemonitor-1.9.0-py2.7.egg to /usr/lib/python2.7/site-packages
Removing simplemonitor 1.10.0rc0 from easy-install.pth file
Adding simplemonitor 1.9.0 to easy-install.pth file
Installing simplemonitor script to /usr/bin
Installing winmonitor script to /usr/bin

Installed /usr/lib/python2.7/site-packages/simplemonitor-1.9.0-py2.7.egg
Processing dependencies for simplemonitor==1.9.0
Searching for psutil
Reading https://pypi.org/simple/psutil/
Downloading https://files.pythonhosted.org/packages/c4/b8/3512f0e93e0db23a71d82485ba256071ebef99b227351f0f5540f744af41/psutil-5.7.0.tar.gz#sha256=685ec16ca14d079455892f25bd124df26ff9137664af445563c1bd36629b5e0e
Best match: psutil 5.7.0
Processing psutil-5.7.0.tar.gz
Writing /tmp/easy_install-eJyVwB/psutil-5.7.0/setup.cfg
Running psutil-5.7.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-eJyVwB/psutil-5.7.0/egg-dist-tmp-6ReOOZ
unable to execute gcc: No such file or directory
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    'pywin32; platform_system=="Windows"',
  File "build/bdist.linux-x86_64/egg/setuptools/__init__.py", line 145, in setup
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 67, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 117, in do_egg_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 424, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 666, in easy_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 713, in install_item
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 758, in process_distribution
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 782, in resolve
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1065, in best_match
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1077, in obtain
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 685, in easy_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 711, in install_item
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 896, in install_eggs
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1164, in build_and_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1150, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 253, in run_setup
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 195, in setup_context
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 166, in save_modules
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 141, in resume
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 154, in save_modules
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 195, in setup_context
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 250, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 45, in _execfile
  File "/tmp/easy_install-eJyVwB/psutil-5.7.0/setup.py", line 426, in <module>
    
  File "/tmp/easy_install-eJyVwB/psutil-5.7.0/setup.py", line 402, in main
    
  File "/tmp/easy_install-eJyVwB/psutil-5.7.0/setup.py", line 116, in missdeps
    
TypeError: hilite() got an unexpected keyword argument 'ok'
```
`
my apology if i am doing something wrong. and let me know how can i fix this. thanks

**Comment by jamesoff** [comment]
Hi there :)

I dropped support for Python 2.7 in the last release. If you have Python 3 (the more recent the better) available please try again with that. Else, version 1.8 was the last version to support 2.7; you can download it from the GitHub releases page: https://github.com/jamesoff/simplemonitor/releases/tag/v1.8 (expand the "Assets" section after the release notes)
